# This is a basic workflow to help you get started with Actions

name: Exam Docker Series CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ exam ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: docker login
        env: 
         DOCKER_USER: ${{ secrets.DOCKER_USER }}   
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build node js
        run: |
           docker build ./frontend -t dushsam/frontendexam:lastest 
           docker build ./backend -t dushsam/backendexam:lastest 
           docker build ./nginx -t dushsam/nginxexam:lastest 
           
      - name: docker push
        run: | 
           docker push dushsam/frontendexam:latest
           docker push dushsam/backendexam:lastest
           docker push dushsam/nginxexam:lastest
